INSERT INTO courses (id, courseName, code, grade, credit) VALUES ('1', 'Introduction to Computer Science', '01418111', 'B+', 2);
INSERT INTO courses (id, courseName, code, grade, credit) VALUES ('2', 'Intellectual Properties and Professional Ethics', '01418141', 'B+', 3);
INSERT INTO courses (id, courseName, code, grade, credit) VALUES ('3', 'Thai Language for Communication', '01999021', 'B', 3);
INSERT INTO courses (id, courseName, code, grade, credit) VALUES ('4', 'Knowledge of the Land', '01999111', 'A', 2);
INSERT INTO courses (id, courseName, code, grade, credit) VALUES ('5', 'Social and Politics', '03751112', 'B', 3);
INSERT INTO courses (id, courseName, code, grade, credit) VALUES ('6', 'English for Everyday Life', '01355101', 'A', 3);
INSERT INTO courses (id, courseName, code, grade, credit) VALUES ('7', 'Calculus I', '01417111', 'A', 3);
INSERT INTO courses (id, courseName, code, grade, credit) VALUES ('8', 'Fundamental Programming Concepts', '01418112', 'A', 3);
INSERT INTO courses (id, courseName, code, grade, credit) VALUES ('9', 'Basic Linear Algebra', '01418112', 'A', 3);
INSERT INTO courses (id, courseName, code, grade, credit) VALUES ('10', 'Economics for Better Living', '01999041', 'C', 3);
INSERT INTO courses (id, courseName, code, grade, credit) VALUES ('11', 'Fundamentals of Computing', '01418132', 'A', 3);
INSERT INTO courses (id, courseName, code, grade, credit) VALUES ('12', 'Golf for Health', '01175163', 'A', 1);
INSERT INTO courses (id, courseName, code, grade, credit) VALUES ('13', 'Computer Programming', '01418113', 'A', 3);
INSERT INTO courses (id, courseName, code, grade, credit) VALUES ('14', 'English for University Life', '01355102', 'B+', 3);
INSERT INTO courses (id, courseName, code, grade, credit) VALUES ('15', 'Aesthetics of Sport', '03654111', 'A', 3);
INSERT INTO courses (id, courseName, code, grade, credit) VALUES ('16', 'Statistical Programming', '01418131', 'A', 3);
INSERT INTO courses (id, courseName, code, grade, credit) VALUES ('17', 'Introduction to Computer Vision', '01418361', 'A', 3);
INSERT INTO courses (id, courseName, code, grade, credit) VALUES ('18', 'Software Construction', '01418211', 'A', 3);
INSERT INTO courses (id, courseName, code, grade, credit) VALUES ('19', 'Health for Life', '01999012', 'A', 3);
INSERT INTO courses (id, courseName, code, grade, credit) VALUES ('20', 'Data Structures and Algorithms', '01418231', 'A', 3);
INSERT INTO courses (id, courseName, code, grade, credit) VALUES ('21', 'Computer Architecture', '01418233', 'A', 3);
INSERT INTO courses (id, courseName, code, grade, credit) VALUES ('22', 'Introduction to Recreation', '01174231', 'B', 2);
