INSERT INTO courses (id, courseName, courseCode, grade, credit) VALUES (DEFAULT(id), 'Introduction to Computer Science', '01418111', 'B+', 2);
INSERT INTO courses (id, courseName, courseCode, grade, credit) VALUES (DEFAULT(id), 'Intellectual Properties and Professional Ethics', '01418141', 'B+', 3);
INSERT INTO courses (id, courseName, courseCode, grade, credit) VALUES (DEFAULT(id), 'Thai Language for Communication', '01999021', 'B', 3);
INSERT INTO courses (id, courseName, courseCode, grade, credit) VALUES (DEFAULT(id), 'Knowledge of the Land', '01999111', 'A', 2);
INSERT INTO courses (id, courseName, courseCode, grade, credit) VALUES (DEFAULT(id), 'Social and Politics', '03751112', 'B', 3);
INSERT INTO courses (id, courseName, courseCode, grade, credit) VALUES (DEFAULT(id), 'English for Everyday Life', '01355101', 'A', 3);
INSERT INTO courses (id, courseName, courseCode, grade, credit) VALUES (DEFAULT(id), 'Calculus I', '01417111', 'A', 3);
INSERT INTO courses (id, courseName, courseCode, grade, credit) VALUES (DEFAULT(id), 'Fundamental Programming Concepts', '01418112', 'A', 3);
INSERT INTO courses (id, courseName, courseCode, grade, credit) VALUES (DEFAULT(id), 'Basic Linear Algebra', '01418112', 'A', 3);
INSERT INTO courses (id, courseName, courseCode, grade, credit) VALUES (DEFAULT(id), 'Economics for Better Living', '01999041', 'C', 3);
INSERT INTO courses (id, courseName, courseCode, grade, credit) VALUES (DEFAULT(id), 'Fundamentals of Computing', '01418132', 'A', 3);
INSERT INTO courses (id, courseName, courseCode, grade, credit) VALUES (DEFAULT(id), 'Golf for Health', '01175163', 'A', 1);
INSERT INTO courses (id, courseName, courseCode, grade, credit) VALUES (DEFAULT(id), 'Computer Programming', '01418113', 'A', 3);
INSERT INTO courses (id, courseName, courseCode, grade, credit) VALUES (DEFAULT(id), 'English for University Life', '01355102', 'B+', 3);
INSERT INTO courses (id, courseName, courseCode, grade, credit) VALUES (DEFAULT(id), 'Aesthetics of Sport', '03654111', 'A', 3);
INSERT INTO courses (id, courseName, courseCode, grade, credit) VALUES (DEFAULT(id), 'Statistical Programming', '01418131', 'A', 3);
INSERT INTO courses (id, courseName, courseCode, grade, credit) VALUES (DEFAULT(id), 'Introduction to Computer Vision', '01418361', 'A', 3);
INSERT INTO courses (id, courseName, courseCode, grade, credit) VALUES (DEFAULT(id), 'Software Construction', '01418211', 'A', 3);
INSERT INTO courses (id, courseName, courseCode, grade, credit) VALUES (DEFAULT(id), 'Health for Life', '01999012', 'A', 3);
INSERT INTO courses (id, courseName, courseCode, grade, credit) VALUES (DEFAULT(id), 'Data Structures and Algorithms', '01418231', 'A', 3);
INSERT INTO courses (id, courseName, courseCode, grade, credit) VALUES (DEFAULT(id), 'Computer Architecture', '01418233', 'A', 3);
INSERT INTO courses (id, courseName, courseCode, grade, credit) VALUES (DEFAULT(id), 'Introduction to Recreation', '01174231', 'B', 2);
